spring:
  application:
    name: ecom-application

  datasource:
    url: jdbc:postgresql://localhost:5432/ecomdb
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL


management:
  endpoints:
    web:
      exposure:
        include: beans,health
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
server:
  info:
    env:
      enabled: true
  shutdown: graceful

info:
  app:
    name: MyNewApp
    description: App build by us
    version: 1.0.0






